name: example
description: A flutterwave example project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutterwave_standard:
    path: "../"
  cupertino_icons: ^1.0.0
  uuid: 3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.4
flutter:

  uses-material-design: true
